import Foundation

// Represents the entire story generated by the AI.
struct Story: Codable, Identifiable, Hashable {
    let id: String  // Unique identifier for the story (e.g., "story_1234567890")
    let title: String // Title of the story
    let template: String // The template used (e.g., "scary story", "evil sorcerer")
    let backgroundMusicPrompt: String? // Story-wide background music prompt
    let scenes: [StoryScene] // Array of scenes composing the story
    let createdAt: Date // Timestamp for when the story was created
    let userId: String // ID of the user who created the story

    // Computed property to generate the JSON representation of the story.
    var jsonRepresentation: String? {
        let encoder = JSONEncoder()
        encoder.outputFormatting = [.prettyPrinted, .sortedKeys] // For readability
        do {
            let jsonData = try encoder.encode(self)
            return String(data: jsonData, encoding: .utf8)
        } catch {
            Log.p(Log.ai_story, Log.process, Log.error, "Could not encode Story to JSON: \(error)")
            return nil
        }
    }
    
    // MARK: - Hashable Conformance
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
    
    static func == (lhs: Story, rhs: Story) -> Bool {
        lhs.id == rhs.id
    }
}

// Represents a single scene within a story.
struct StoryScene: Codable, Identifiable, Hashable {
    let id: String // Unique identifier for the scene (e.g., "scene_1", "scene_2")
    let sceneNumber: Int // Order of the scene in the story
    let narration: String? // Text for the narration of this scene
    let voice: String? // The AI voice to use (e.g., "ElevenLabs Adam", "TikTok Voice 4")
    let visualPrompt: String // Prompt for the video/image generation (the "storyboard" part)
    let audioPrompt: String? // Prompt for background music or sound effects (optional)
    let duration: Double? // Estimated duration of the scene in seconds (optional, for later use)
    
    // MARK: - Hashable Conformance
    
    func hash(into hasher: inout Hasher) {
        hasher.combine(id)
    }
    
    static func == (lhs: StoryScene, rhs: StoryScene) -> Bool {
        lhs.id == rhs.id
    }
}

// MARK: - Preview Data
extension Story {
    static var previewStories: [Story] = [
        Story(
            id: "story1",
            title: "Space Adventure",
            template: "adventure",
            backgroundMusicPrompt: "Epic orchestral music with a sense of wonder",
            scenes: [
                StoryScene(
                    id: "scene1",
                    sceneNumber: 1,
                    narration: "Our journey begins in the vast expanse of space",
                    voice: "ElevenLabs Brian",
                    visualPrompt: "A stunning view of Earth from space, with stars twinkling in the background",
                    audioPrompt: "Gentle whooshing of spacecraft engines",
                    duration: 5
                ),
                StoryScene(
                    id: "scene2",
                    sceneNumber: 2,
                    narration: "A mysterious signal catches our attention",
                    voice: "ElevenLabs Brian",
                    visualPrompt: "A glowing alien artifact floating in space, emitting pulses of blue light",
                    audioPrompt: "Mysterious pulsing sounds with space ambience",
                    duration: 5
                )
            ],
            createdAt: Date(),
            userId: "preview_user"
        ),
        Story(
            id: "story2",
            title: "Urban Legend",
            template: "mystery",
            backgroundMusicPrompt: "Dark ambient music with suspenseful undertones",
            scenes: [
                StoryScene(
                    id: "scene3",
                    sceneNumber: 1,
                    narration: "In the heart of the city, a legend persists",
                    voice: "ElevenLabs Rachel",
                    visualPrompt: "A foggy city street at night, with vintage lampposts casting eerie shadows",
                    audioPrompt: "City ambience with distant sirens",
                    duration: 5
                )
            ],
            createdAt: Date().addingTimeInterval(-86400), // 1 day ago
            userId: "preview_user"
        )
    ]
} 